/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ClinicIndexRouteImport } from './routes/clinic.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OrderConfirmationIdRouteImport } from './routes/order-confirmation.$id'
import { Route as ClinicVaccinationsRouteImport } from './routes/clinic.vaccinations'
import { Route as ClinicDoctorsRouteImport } from './routes/clinic.doctors'
import { Route as ClinicBookRouteImport } from './routes/clinic.book'
import { Route as ClinicAppointmentsRouteImport } from './routes/clinic.appointments'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ClinicDoctorsIndexRouteImport } from './routes/clinic.doctors.index'
import { Route as ClinicAppointmentsIndexRouteImport } from './routes/clinic.appointments.index'
import { Route as ShopProductIdRouteImport } from './routes/shop.product.$id'
import { Route as ShopCategorySlugRouteImport } from './routes/shop.category.$slug'
import { Route as ClinicDoctorsIdRouteImport } from './routes/clinic.doctors.$id'
import { Route as ClinicAppointmentsIdRouteImport } from './routes/clinic.appointments.$id'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ClinicIndexRoute = ClinicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationIdRoute = OrderConfirmationIdRouteImport.update({
  id: '/order-confirmation/$id',
  path: '/order-confirmation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicVaccinationsRoute = ClinicVaccinationsRouteImport.update({
  id: '/vaccinations',
  path: '/vaccinations',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicDoctorsRoute = ClinicDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicBookRoute = ClinicBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ClinicRoute,
} as any)
const ClinicAppointmentsRoute = ClinicAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => ClinicRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ClinicDoctorsIndexRoute = ClinicDoctorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicDoctorsRoute,
} as any)
const ClinicAppointmentsIndexRoute = ClinicAppointmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicAppointmentsRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => ShopRoute,
} as any)
const ShopCategorySlugRoute = ShopCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ClinicDoctorsIdRoute = ClinicDoctorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClinicDoctorsRoute,
} as any)
const ClinicAppointmentsIdRoute = ClinicAppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClinicAppointmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/clinic': typeof ClinicRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/clinic/appointments': typeof ClinicAppointmentsRouteWithChildren
  '/clinic/book': typeof ClinicBookRoute
  '/clinic/doctors': typeof ClinicDoctorsRouteWithChildren
  '/clinic/vaccinations': typeof ClinicVaccinationsRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/clinic/': typeof ClinicIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/clinic/appointments/$id': typeof ClinicAppointmentsIdRoute
  '/clinic/doctors/$id': typeof ClinicDoctorsIdRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/clinic/appointments/': typeof ClinicAppointmentsIndexRoute
  '/clinic/doctors/': typeof ClinicDoctorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/clinic/book': typeof ClinicBookRoute
  '/clinic/vaccinations': typeof ClinicVaccinationsRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/clinic': typeof ClinicIndexRoute
  '/shop': typeof ShopIndexRoute
  '/clinic/appointments/$id': typeof ClinicAppointmentsIdRoute
  '/clinic/doctors/$id': typeof ClinicDoctorsIdRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/clinic/appointments': typeof ClinicAppointmentsIndexRoute
  '/clinic/doctors': typeof ClinicDoctorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/clinic': typeof ClinicRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/shop': typeof ShopRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/clinic/appointments': typeof ClinicAppointmentsRouteWithChildren
  '/clinic/book': typeof ClinicBookRoute
  '/clinic/doctors': typeof ClinicDoctorsRouteWithChildren
  '/clinic/vaccinations': typeof ClinicVaccinationsRoute
  '/order-confirmation/$id': typeof OrderConfirmationIdRoute
  '/orders/$id': typeof OrdersIdRoute
  '/clinic/': typeof ClinicIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/clinic/appointments/$id': typeof ClinicAppointmentsIdRoute
  '/clinic/doctors/$id': typeof ClinicDoctorsIdRoute
  '/shop/category/$slug': typeof ShopCategorySlugRoute
  '/shop/product/$id': typeof ShopProductIdRoute
  '/clinic/appointments/': typeof ClinicAppointmentsIndexRoute
  '/clinic/doctors/': typeof ClinicDoctorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/clinic'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/services'
    | '/shop'
    | '/blog/$slug'
    | '/clinic/appointments'
    | '/clinic/book'
    | '/clinic/doctors'
    | '/clinic/vaccinations'
    | '/order-confirmation/$id'
    | '/orders/$id'
    | '/clinic/'
    | '/shop/'
    | '/clinic/appointments/$id'
    | '/clinic/doctors/$id'
    | '/shop/category/$slug'
    | '/shop/product/$id'
    | '/clinic/appointments/'
    | '/clinic/doctors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/services'
    | '/blog/$slug'
    | '/clinic/book'
    | '/clinic/vaccinations'
    | '/order-confirmation/$id'
    | '/orders/$id'
    | '/clinic'
    | '/shop'
    | '/clinic/appointments/$id'
    | '/clinic/doctors/$id'
    | '/shop/category/$slug'
    | '/shop/product/$id'
    | '/clinic/appointments'
    | '/clinic/doctors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/clinic'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/services'
    | '/shop'
    | '/blog/$slug'
    | '/clinic/appointments'
    | '/clinic/book'
    | '/clinic/doctors'
    | '/clinic/vaccinations'
    | '/order-confirmation/$id'
    | '/orders/$id'
    | '/clinic/'
    | '/shop/'
    | '/clinic/appointments/$id'
    | '/clinic/doctors/$id'
    | '/shop/category/$slug'
    | '/shop/product/$id'
    | '/clinic/appointments/'
    | '/clinic/doctors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ClinicRoute: typeof ClinicRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  ShopRoute: typeof ShopRouteWithChildren
  OrderConfirmationIdRoute: typeof OrderConfirmationIdRoute
  OrdersIdRoute: typeof OrdersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/clinic/': {
      id: '/clinic/'
      path: '/'
      fullPath: '/clinic/'
      preLoaderRoute: typeof ClinicIndexRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$id': {
      id: '/order-confirmation/$id'
      path: '/order-confirmation/$id'
      fullPath: '/order-confirmation/$id'
      preLoaderRoute: typeof OrderConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/vaccinations': {
      id: '/clinic/vaccinations'
      path: '/vaccinations'
      fullPath: '/clinic/vaccinations'
      preLoaderRoute: typeof ClinicVaccinationsRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/clinic/doctors': {
      id: '/clinic/doctors'
      path: '/doctors'
      fullPath: '/clinic/doctors'
      preLoaderRoute: typeof ClinicDoctorsRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/clinic/book': {
      id: '/clinic/book'
      path: '/book'
      fullPath: '/clinic/book'
      preLoaderRoute: typeof ClinicBookRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/clinic/appointments': {
      id: '/clinic/appointments'
      path: '/appointments'
      fullPath: '/clinic/appointments'
      preLoaderRoute: typeof ClinicAppointmentsRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/clinic/doctors/': {
      id: '/clinic/doctors/'
      path: '/'
      fullPath: '/clinic/doctors/'
      preLoaderRoute: typeof ClinicDoctorsIndexRouteImport
      parentRoute: typeof ClinicDoctorsRoute
    }
    '/clinic/appointments/': {
      id: '/clinic/appointments/'
      path: '/'
      fullPath: '/clinic/appointments/'
      preLoaderRoute: typeof ClinicAppointmentsIndexRouteImport
      parentRoute: typeof ClinicAppointmentsRoute
    }
    '/shop/product/$id': {
      id: '/shop/product/$id'
      path: '/product/$id'
      fullPath: '/shop/product/$id'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/category/$slug': {
      id: '/shop/category/$slug'
      path: '/category/$slug'
      fullPath: '/shop/category/$slug'
      preLoaderRoute: typeof ShopCategorySlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/clinic/doctors/$id': {
      id: '/clinic/doctors/$id'
      path: '/$id'
      fullPath: '/clinic/doctors/$id'
      preLoaderRoute: typeof ClinicDoctorsIdRouteImport
      parentRoute: typeof ClinicDoctorsRoute
    }
    '/clinic/appointments/$id': {
      id: '/clinic/appointments/$id'
      path: '/$id'
      fullPath: '/clinic/appointments/$id'
      preLoaderRoute: typeof ClinicAppointmentsIdRouteImport
      parentRoute: typeof ClinicAppointmentsRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ClinicAppointmentsRouteChildren {
  ClinicAppointmentsIdRoute: typeof ClinicAppointmentsIdRoute
  ClinicAppointmentsIndexRoute: typeof ClinicAppointmentsIndexRoute
}

const ClinicAppointmentsRouteChildren: ClinicAppointmentsRouteChildren = {
  ClinicAppointmentsIdRoute: ClinicAppointmentsIdRoute,
  ClinicAppointmentsIndexRoute: ClinicAppointmentsIndexRoute,
}

const ClinicAppointmentsRouteWithChildren =
  ClinicAppointmentsRoute._addFileChildren(ClinicAppointmentsRouteChildren)

interface ClinicDoctorsRouteChildren {
  ClinicDoctorsIdRoute: typeof ClinicDoctorsIdRoute
  ClinicDoctorsIndexRoute: typeof ClinicDoctorsIndexRoute
}

const ClinicDoctorsRouteChildren: ClinicDoctorsRouteChildren = {
  ClinicDoctorsIdRoute: ClinicDoctorsIdRoute,
  ClinicDoctorsIndexRoute: ClinicDoctorsIndexRoute,
}

const ClinicDoctorsRouteWithChildren = ClinicDoctorsRoute._addFileChildren(
  ClinicDoctorsRouteChildren,
)

interface ClinicRouteChildren {
  ClinicAppointmentsRoute: typeof ClinicAppointmentsRouteWithChildren
  ClinicBookRoute: typeof ClinicBookRoute
  ClinicDoctorsRoute: typeof ClinicDoctorsRouteWithChildren
  ClinicVaccinationsRoute: typeof ClinicVaccinationsRoute
  ClinicIndexRoute: typeof ClinicIndexRoute
}

const ClinicRouteChildren: ClinicRouteChildren = {
  ClinicAppointmentsRoute: ClinicAppointmentsRouteWithChildren,
  ClinicBookRoute: ClinicBookRoute,
  ClinicDoctorsRoute: ClinicDoctorsRouteWithChildren,
  ClinicVaccinationsRoute: ClinicVaccinationsRoute,
  ClinicIndexRoute: ClinicIndexRoute,
}

const ClinicRouteWithChildren =
  ClinicRoute._addFileChildren(ClinicRouteChildren)

interface ShopRouteChildren {
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCategorySlugRoute: typeof ShopCategorySlugRoute
  ShopProductIdRoute: typeof ShopProductIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIndexRoute: ShopIndexRoute,
  ShopCategorySlugRoute: ShopCategorySlugRoute,
  ShopProductIdRoute: ShopProductIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ClinicRoute: ClinicRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  ShopRoute: ShopRouteWithChildren,
  OrderConfirmationIdRoute: OrderConfirmationIdRoute,
  OrdersIdRoute: OrdersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
